"""
Publisher — renders summaries to Markdown/HTML and pushes to GitHub Pages.
"""

import subprocess
import logging
import tempfile
import shutil
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent
OUTPUT_DIR = BASE_DIR / "output"


class Publisher:
    def __init__(self, output_config: dict):
        self.config = output_config
        self.gh_pages = output_config.get("github_pages", {})

    def publish(self, results: list):
        OUTPUT_DIR.mkdir(exist_ok=True)
        date_str = datetime.utcnow().strftime("%Y-%m-%d")

        # Write individual summary files
        for r in results:
            bill = r["bill"]
            summary = r["summary"]
            safe_id = bill["id"].replace("/", "-").replace(" ", "_")
            out_file = OUTPUT_DIR / f"{safe_id}.md"

            with open(out_file, "w") as f:
                f.write(f"# {bill['title']}\n\n")
                f.write(f"**Source:** {bill['source']}  \n")
                f.write(f"**Status:** {bill['status']}  \n")
                f.write(f"**Tags:** {', '.join(bill.get('tags', []))}  \n")
                f.write(f"**URL:** [{bill['url']}]({bill['url']})  \n\n")
                f.write("---\n\n")
                f.write(summary)
                f.write("\n")

        # Write index
        self._write_index(results, date_str)

        # Push to GitHub Pages
        if self.gh_pages.get("enabled"):
            self._push_github_pages(date_str)

    def _write_index(self, results: list, date_str: str):
        index_path = OUTPUT_DIR / "index.md"
        with open(index_path, "w") as f:
            f.write(f"# Plain Law — {date_str}\n\n")
            f.write("Plain-language summaries of legislation, generated by a local Gemma model.\n\n")
            f.write("---\n\n")
            for r in results:
                bill = r["bill"]
                safe_id = bill["id"].replace("/", "-").replace(" ", "_")
                f.write(f"- [{bill['title']}]({safe_id}.md) — *{bill['source']}*\n")

    def _push_github_pages(self, date_str: str):
        repo = self.gh_pages.get("repo")
        branch = self.gh_pages.get("branch", "gh-pages")
        commit_msg = self.gh_pages.get("commit_message", f"chore: update summaries [{date_str}]").replace("{date}", date_str)

        if not repo:
            logging.warning("GitHub Pages repo not configured — skipping push")
            return

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                subprocess.run(["git", "clone", f"git@github.com:{repo}.git", "--branch", branch, tmpdir], check=True)
                # Copy output files
                for f in OUTPUT_DIR.glob("*.md"):
                    shutil.copy(f, tmpdir)
                # Commit and push
                subprocess.run(["git", "-C", tmpdir, "add", "."], check=True)
                subprocess.run(["git", "-C", tmpdir, "commit", "-m", commit_msg], check=True)
                subprocess.run(["git", "-C", tmpdir, "push", "origin", branch], check=True)
            logging.info(f"Pushed to GitHub Pages: {repo}@{branch}")
        except subprocess.CalledProcessError as e:
            logging.error(f"GitHub Pages push failed: {e}")
