"""
Publisher — renders summaries to Markdown/HTML and streams to GitHub Pages.

Streaming mode (default):
  - Call publish_one(result) for each bill as soon as Gemma finishes it.
  - Each call appends one JSON line to bills.jsonl and commits+pushes immediately.
  - The site updates in near real-time; partial runs publish what completed.

Batch mode (legacy / --dry-run):
  - Call publish(results) with the full list.
  - Writes bills.jsonl once, then does a single commit+push.
"""

import json
import subprocess
import logging
import tempfile
import shutil
from pathlib import Path
from datetime import datetime, timezone

BASE_DIR = Path(__file__).parent.parent
OUTPUT_DIR = BASE_DIR / "output"
JSONL_PATH = OUTPUT_DIR / "bills.jsonl"


class Publisher:
    def __init__(self, output_config: dict):
        self.config = output_config
        self.gh_pages = output_config.get("github_pages", {})
        self._clone_dir: str | None = None  # reused across streaming calls

    # ── Public API ────────────────────────────────────────────────────────────

    def publish_one(self, result: dict):
        """Stream a single summarised bill: write files, append JSONL, commit+push."""
        OUTPUT_DIR.mkdir(exist_ok=True)
        self._write_md(result)
        entry = self._build_entry(result)
        self._append_jsonl(entry)
        if self.gh_pages.get("enabled"):
            self._stream_push(result["bill"]["id"])

    def publish(self, results: list):
        """Batch publish (legacy path). Writes all files then does one commit."""
        OUTPUT_DIR.mkdir(exist_ok=True)
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        # Wipe existing JSONL so we start clean on a batch run
        if JSONL_PATH.exists():
            JSONL_PATH.unlink()

        for r in results:
            self._write_md(r)
            entry = self._build_entry(r)
            self._append_jsonl(entry)

        self._write_index(results, date_str)

        if self.gh_pages.get("enabled"):
            self._batch_push(date_str)

    # ── Entry builder ─────────────────────────────────────────────────────────

    def _build_entry(self, result: dict) -> dict:
        bill = result["bill"]
        source_locale = result.get("source", {})
        summary = result["summary"]
        level = source_locale.get("type", "federal")
        safe_id = self._safe_id(bill["id"])
        return {
            "id":          bill.get("id", ""),
            "title":       bill.get("title", ""),
            "summary":     summary,
            "status":      bill.get("status", ""),
            "status_date": bill.get("status_date", ""),
            "source":      bill.get("source", source_locale.get("name", "")),
            "url":         bill.get("url", ""),
            "level":       level,
            "state":       source_locale.get("state", ""),
            "tags":        bill.get("tags", []),
            "file":        f"{safe_id}.md",
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }

    # ── File writers ──────────────────────────────────────────────────────────

    def _write_md(self, result: dict):
        bill = result["bill"]
        summary = result["summary"]
        safe_id = self._safe_id(bill["id"])
        out_file = OUTPUT_DIR / f"{safe_id}.md"

        with open(out_file, "w") as f:
            f.write(f"# {bill['title']}\n\n")
            f.write("> ⚠️ **AI-generated summary.** Always verify with the official source before acting on this information.\n>\n")
            if bill.get("url"):
                f.write(f"> 📄 **Official source:** [{bill['url']}]({bill['url']})\n\n")
            else:
                f.write("> 📄 **Official source:** Not available — search your legislature's website directly.\n\n")
            f.write("---\n\n")
            f.write(summary)
            f.write("\n\n---\n\n")
            f.write("## Source & Verification\n\n")
            f.write("| Field | Value |\n")
            f.write("|-------|-------|\n")
            f.write(f"| **Source** | {bill['source']} |\n")
            status_str = bill.get("status", "Unknown")
            if bill.get("status_date"):
                status_str += f" *(as of {bill['status_date']})*"
            f.write(f"| **Status** | {status_str} |\n")
            if bill.get("url"):
                f.write(f"| **Official text** | [{bill['url']}]({bill['url']}) |\n")
            f.write(f"| **Tags** | {', '.join(bill.get('tags', []))} |\n")
            f.write(f"| **Summary generated** | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} |\n")
            f.write("| **Model** | Gemma (local, via Ollama) |\n\n")
            f.write("*This summary was generated by a local AI model and has not been reviewed by a lawyer or "
                    "policy expert. It may contain errors or omissions. Read the official text before making decisions.*\n")

    def _append_jsonl(self, entry: dict):
        with open(JSONL_PATH, "a") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        logging.debug(f"Appended to bills.jsonl: {entry['id']}")

    def _write_index(self, results: list, date_str: str):
        index_path = OUTPUT_DIR / "index.md"
        with open(index_path, "w") as f:
            f.write(f"# Plain Law — {date_str}\n\n")
            f.write("Plain-language summaries of legislation, generated by a local Gemma model.\n\n")
            f.write("> ⚠️ These summaries are AI-generated and may contain errors. "
                    "Each entry links to its official source — always read the original before acting on this information.\n\n")
            f.write("---\n\n")
            by_source: dict[str, list] = {}
            for r in results:
                src = r["bill"]["source"]
                by_source.setdefault(src, []).append(r)
            for src, items in sorted(by_source.items()):
                f.write(f"### {src}\n\n")
                for r in items:
                    bill = r["bill"]
                    safe_id = self._safe_id(bill["id"])
                    official = f" — [official source]({bill['url']})" if bill.get("url") else ""
                    f.write(f"- [{bill['title']}]({safe_id}.md){official}\n")
                f.write("\n")

    # ── Git helpers ───────────────────────────────────────────────────────────

    def _get_clone(self) -> str:
        """Return path to a persistent clone dir; create+clone on first call."""
        if self._clone_dir and Path(self._clone_dir).exists():
            return self._clone_dir

        repo = self.gh_pages.get("repo")
        branch = self.gh_pages.get("branch", "gh-pages")
        if not repo:
            raise ValueError("GitHub Pages repo not configured")

        tmpdir = tempfile.mkdtemp(prefix="plain-law-pages-")
        subprocess.run(
            ["git", "clone", f"git@github.com:{repo}.git", "--branch", branch, "--depth", "1", tmpdir],
            check=True,
        )
        self._clone_dir = tmpdir
        logging.info(f"Cloned {repo}@{branch} → {tmpdir}")
        return tmpdir

    def _stream_push(self, bill_id: str):
        """Copy changed files into the persistent clone and push one commit."""
        try:
            clone = self._get_clone()
            bill = bill_id  # for the commit message

            # Copy the new/changed files
            safe_id = self._safe_id(bill)
            md_src = OUTPUT_DIR / f"{safe_id}.md"
            if md_src.exists():
                shutil.copy(md_src, clone)

            if JSONL_PATH.exists():
                shutil.copy(JSONL_PATH, clone)

            # Stage, commit, push
            subprocess.run(["git", "-C", clone, "add", "."], check=True)

            # Check if there's anything to commit (git returns 1 if nothing staged)
            diff = subprocess.run(
                ["git", "-C", clone, "diff", "--cached", "--quiet"],
                capture_output=True,
            )
            if diff.returncode == 0:
                logging.debug(f"Nothing new to commit for {bill_id}")
                return

            msg = f"feat: add summary for {bill_id}"
            subprocess.run(["git", "-C", clone, "commit", "-m", msg], check=True)
            subprocess.run(["git", "-C", clone, "push", "origin", self.gh_pages.get("branch", "gh-pages")], check=True)
            logging.info(f"Pushed stream commit: {msg}")

        except subprocess.CalledProcessError as e:
            logging.error(f"Stream push failed for {bill_id}: {e}")

    def _batch_push(self, date_str: str):
        """One-shot clone, copy all output, commit, push."""
        repo = self.gh_pages.get("repo")
        branch = self.gh_pages.get("branch", "gh-pages")
        raw_msg = self.gh_pages.get("commit_message", "chore: update summaries [{date}]")
        commit_msg = raw_msg.replace("{date}", date_str)

        if not repo:
            logging.warning("GitHub Pages repo not configured — skipping push")
            return

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                subprocess.run(
                    ["git", "clone", f"git@github.com:{repo}.git", "--branch", branch, tmpdir],
                    check=True,
                )
                for f in OUTPUT_DIR.glob("*.md"):
                    shutil.copy(f, tmpdir)
                if JSONL_PATH.exists():
                    shutil.copy(JSONL_PATH, tmpdir)
                subprocess.run(["git", "-C", tmpdir, "add", "."], check=True)
                subprocess.run(["git", "-C", tmpdir, "commit", "-m", commit_msg], check=True)
                subprocess.run(["git", "-C", tmpdir, "push", "origin", branch], check=True)
            logging.info(f"Batch pushed to GitHub Pages: {repo}@{branch}")
        except subprocess.CalledProcessError as e:
            logging.error(f"GitHub Pages batch push failed: {e}")

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _safe_id(bill_id: str) -> str:
        return bill_id.replace("/", "-").replace(" ", "_")
